services:
  main:
    container_name: main
    build:
      context: .
      dockerfile_inline: |
        FROM neo4j:latest
        RUN neo4j start
        RUN apt-get update && apt-get install -y python3 python3-pip
        RUN pip install --upgrade pip
        RUN pip install neo4j graphdatascience torch
    environment:
      - NEO4J_AUTH=none
      - NEO4J_PLUGINS='["graph-data-science"]'
      - NEO4J_server_config_strict__validation_enabled=false
      - NEO4J_server_memory_transaction_total_max=2G
      - NEO4J_server_memory_heap_initial_size=1G
      - NEO4J_server_memory_heap_max_size=1G
      - NEO4J_server_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_initial_size=1G
      - NEO4J_dbms_memory_heap_max_size=1G
      - NEO4J_dbms_memory_pagecache_size=1G
    volumes:
      - type: bind
        source: .
        target: /workspace
    working_dir: /workspace
    ports:
      - "7474:7474"
      - "7687:7687"
    command: ["neo4j", "start"]
