services:
  main:
    container_name: main
    build:
      context: .
      dockerfile_inline: |
        FROM neo4j:latest
        RUN neo4j start
        RUN apt-get update && apt-get install -y python3 python3-pip
        RUN pip3 install neo4j

    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - type: bind
        source: .
        target: /workspace
    working_dir: /workspace

    ports:
      - "7474:7474"
      - "7687:7687"

    command: ["tail", "-f", "/dev/null"]
